/**
 * 세분화 한국사 연표 시드 (멱등, 백업후교체).
 *
 * 실행: npm run seed:timeline   (.env.local 자격증명 필요)
 *
 * 동작(사용자 승인된 backup-then-replace):
 *  1) 현재 facts 전부를 읽어 scripts/facts-backup-prev.json 으로 백업("backed up N").
 *  2) facts 의 기존 문서를 모두 삭제(배치 <=400).
 *  3) 안정 slug id 로 세분화 연표를 삽입(db.collection("facts").doc(slug).set(...)).
 *  4) "deleted N, inserted M" 출력.
 *
 * 안정 id(slug) 사용 → 재실행 시 동일 결과(중복 생성 없음). 매 실행 백업 보존.
 * 가드: FIRESTORE_DATABASE_ID 또는 FIREBASE_STORAGE_BUCKET 미설정 시 throw.
 */
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { Timestamp } from "firebase-admin/firestore";
import { db } from "../src/lib/firebase-admin.ts";

interface SeedFact {
  slug: string; // 안정 문서 id: <era>-<year>-<keyword> (중복 금지)
  era: string; // ERA_KEYS 중 하나
  year: number | null; // BC = 음수
  title: string;
  kind: string; // event | person | system | culture | war | foreign
  period: string | null; // 시대별 일관된 소시대 라벨
  category: string; // 정치 | 경제 | 사회 | 문화 | 대외관계
  importance: number; // 3=최빈출, 2=빈출, 1=보조
  body: string; // 1-2 문장
  keywords: string[]; // 인물·사건·제도·문화재 등 매칭용 핵심어(풍부하게)
  relatedTo?: string[];
}

const FACTS: SeedFact[] = [
  // ==================== 선사 시대 (prehistoric) ====================
  {
    slug: "prehistoric-700000-구석기",
    era: "prehistoric",
    year: -700000,
    title: "구석기 시대 시작",
    kind: "culture",
    period: "선사-구석기",
    category: "사회",
    importance: 3,
    body: "약 70만 년 전부터 뗀석기를 사용하며 사냥과 채집으로 이동 생활을 하였다. 동굴·막집에 거주하였다.",
    keywords: ["구석기", "뗀석기", "주먹도끼", "슴베찌르개", "공주 석장리", "연천 전곡리", "동굴", "막집", "이동 생활", "사냥", "채집"],
  },
  {
    slug: "prehistoric-8000-신석기",
    era: "prehistoric",
    year: -8000,
    title: "신석기 시대 시작",
    kind: "culture",
    period: "선사-신석기",
    category: "경제",
    importance: 3,
    body: "기원전 8000년경부터 간석기와 빗살무늬 토기를 사용하고 농경과 정착 생활이 시작되었다. 가락바퀴로 옷을 지었다.",
    keywords: ["신석기", "간석기", "빗살무늬 토기", "농경", "정착", "움집", "가락바퀴", "조개껍데기 가면", "서울 암사동", "부산 동삼동", "신석기 혁명", "애니미즘", "토테미즘"],
  },
  {
    slug: "prehistoric-2000-청동기",
    era: "prehistoric",
    year: -2000,
    title: "청동기 시대 시작",
    kind: "culture",
    period: "선사-청동기",
    category: "사회",
    importance: 3,
    body: "청동기 사용과 벼농사 시작으로 계급이 발생하고 군장(족장)이 등장하였다. 민무늬 토기·반달 돌칼을 사용하였다.",
    keywords: ["청동기", "비파형 동검", "민무늬 토기", "반달 돌칼", "고인돌", "벼농사", "계급 발생", "군장", "거푸집", "탁자식 고인돌", "선민사상"],
  },
  {
    slug: "prehistoric-500-철기",
    era: "prehistoric",
    year: -500,
    title: "철기 시대 시작",
    kind: "culture",
    period: "선사-철기",
    category: "대외관계",
    importance: 2,
    body: "기원전 5세기경 철제 농기구·무기가 보급되고, 명도전·반량전 등 중국 화폐와 붓(창원 다호리)으로 중국과의 교류·한자 사용을 보여준다.",
    keywords: ["철기", "세형 동검", "거푸집", "명도전", "반량전", "오수전", "붓", "창원 다호리", "독무덤", "널무덤", "잔무늬 거울"],
  },
  {
    slug: "prehistoric-6000-신석기농경",
    era: "prehistoric",
    year: -6000,
    title: "신석기 농경과 토기",
    kind: "culture",
    period: "선사-신석기",
    category: "사회",
    importance: 2,
    body: "조·피 등을 재배하는 원시 농경과 갈돌·갈판을 사용하였고, 이른 민무늬 토기·덧무늬 토기에서 빗살무늬 토기로 발전하였다.",
    keywords: ["조", "피", "원시 농경", "갈돌", "갈판", "덧무늬 토기", "이른 민무늬 토기", "빗살무늬 토기", "신석기", "움집"],
  },
  {
    slug: "prehistoric-1500-고인돌",
    era: "prehistoric",
    year: -1500,
    title: "고인돌과 군장 사회",
    kind: "culture",
    period: "선사-청동기",
    category: "정치",
    importance: 2,
    body: "거대한 고인돌과 돌널무덤은 지배층(군장)의 권력을 보여주며, 청동기 시대 계급 분화와 사유 재산의 발생을 반영한다.",
    keywords: ["고인돌", "돌널무덤", "군장", "계급 분화", "사유 재산", "탁자식", "바둑판식", "지배층", "강화 부근리"],
  },

  // ==================== 고조선·연맹왕국 (gojoseon) ====================
  {
    slug: "gojoseon--2333-건국",
    era: "gojoseon",
    year: -2333,
    title: "고조선 건국",
    kind: "event",
    period: "고조선-건국기",
    category: "정치",
    importance: 3,
    body: "단군왕검이 아사달에 도읍하여 우리 역사상 최초의 국가 고조선을 건국하였다고 전한다. 8조법으로 사회를 통치하였다.",
    keywords: ["단군왕검", "고조선", "아사달", "8조법", "단군 신화", "홍익인간", "제정일치", "삼국유사", "비파형 동검", "탁자식 고인돌"],
    relatedTo: ["위만 집권"],
  },
  {
    slug: "gojoseon--194-위만",
    era: "gojoseon",
    year: -194,
    title: "위만 집권",
    kind: "person",
    period: "고조선-위만조선기",
    category: "정치",
    importance: 2,
    body: "위만이 준왕을 몰아내고 고조선의 왕이 되어 철기 문화를 본격 수용하고 중계 무역으로 번성하였다.",
    keywords: ["위만", "위만조선", "준왕", "철기", "중계 무역", "왕검성"],
    relatedTo: ["고조선 건국", "고조선 멸망"],
  },
  {
    slug: "gojoseon--108-멸망",
    era: "gojoseon",
    year: -108,
    title: "고조선 멸망",
    kind: "war",
    period: "고조선-위만조선기",
    category: "대외관계",
    importance: 3,
    body: "한 무제의 침공으로 왕검성이 함락되어 고조선이 멸망하고 한 군현(낙랑 등)이 설치되었다.",
    keywords: ["한 무제", "왕검성", "고조선 멸망", "한 군현", "낙랑군", "우거왕"],
    relatedTo: ["위만 집권"],
  },
  {
    slug: "gojoseon--100-부여",
    era: "gojoseon",
    year: -100,
    title: "부여",
    kind: "system",
    period: "연맹왕국기",
    category: "정치",
    importance: 2,
    body: "만주 쑹화강 유역의 연맹왕국으로 마가·우가·저가·구가의 사출도와 영고(제천 행사)·순장·1책 12법이 특징이다.",
    keywords: ["부여", "사출도", "마가", "우가", "저가", "구가", "영고", "순장", "1책 12법", "쑹화강", "연맹왕국"],
  },
  {
    slug: "gojoseon--37-고구려연맹",
    era: "gojoseon",
    year: -37,
    title: "고구려 건국(연맹)",
    kind: "system",
    period: "연맹왕국기",
    category: "정치",
    importance: 2,
    body: "주몽이 졸본에서 고구려를 세웠으며 제가 회의, 동맹(제천 행사), 서옥제(데릴사위제)의 풍습이 있었다.",
    keywords: ["주몽", "고구려", "졸본", "제가 회의", "동맹", "서옥제", "데릴사위제", "5부족 연맹"],
  },
  {
    slug: "gojoseon--50-삼한",
    era: "gojoseon",
    year: -50,
    title: "삼한",
    kind: "system",
    period: "연맹왕국기",
    category: "사회",
    importance: 2,
    body: "마한·진한·변한으로 제정 분리(천군·소도)가 이루어졌고, 변한의 철 생산과 수릿날·계절제 같은 농경 의례가 발달하였다.",
    keywords: ["삼한", "마한", "진한", "변한", "천군", "소도", "제정 분리", "철 생산", "덩이쇠", "수릿날", "계절제", "목지국"],
  },
  {
    slug: "gojoseon--30-옥저동예",
    era: "gojoseon",
    year: -30,
    title: "옥저·동예",
    kind: "system",
    period: "연맹왕국기",
    category: "사회",
    importance: 2,
    body: "옥저는 민며느리제·가족 공동 무덤, 동예는 책화·족외혼과 무천(제천 행사), 단궁·과하마·반어피 특산물이 특징이다.",
    keywords: ["옥저", "동예", "민며느리제", "가족 공동 무덤", "책화", "족외혼", "무천", "단궁", "과하마", "반어피", "군장 국가"],
  },

  // ==================== 삼국 시대 (samguk) ====================
  {
    slug: "samguk-42-금관가야",
    era: "samguk",
    year: 42,
    title: "금관가야 건국",
    kind: "event",
    period: "삼국-성립기",
    category: "정치",
    importance: 2,
    body: "김수로왕이 김해에서 금관가야를 세워 전기 가야 연맹을 주도하였으며, 철 생산과 해상 중계 무역으로 번영하였다.",
    keywords: ["금관가야", "김수로왕", "김해", "전기 가야 연맹", "철 생산", "덩이쇠", "구지가", "낙랑·왜 중계 무역", "대성동 고분"],
  },
  {
    slug: "samguk-562-대가야",
    era: "samguk",
    year: 562,
    title: "대가야 멸망",
    kind: "war",
    period: "삼국-전성기",
    category: "대외관계",
    importance: 2,
    body: "후기 가야 연맹을 이끌던 고령의 대가야가 신라 진흥왕에게 정복되면서 가야 연맹이 완전히 해체되었다.",
    keywords: ["대가야", "고령", "후기 가야 연맹", "진흥왕", "가야 멸망", "이사부", "우륵", "가야금", "지산동 고분"],
  },
  {
    slug: "samguk-194-진대법",
    era: "samguk",
    year: 194,
    title: "고구려 진대법",
    kind: "system",
    period: "삼국-성립기",
    category: "경제",
    importance: 2,
    body: "고국천왕이 을파소의 건의로 봄에 곡식을 빌려주고 가을에 갚게 하는 빈민 구제 제도인 진대법을 실시하였다.",
    keywords: ["고국천왕", "을파소", "진대법", "빈민 구제", "춘대추납"],
  },
  {
    slug: "samguk-260-백제율령",
    era: "samguk",
    year: 260,
    title: "백제 고이왕 체제 정비",
    kind: "system",
    period: "삼국-성립기",
    category: "정치",
    importance: 2,
    body: "고이왕이 관등제(6좌평 16관등)와 관복제를 마련하고 율령의 기틀을 세워 중앙집권의 토대를 닦았다.",
    keywords: ["고이왕", "6좌평", "16관등", "관복제", "백제", "한강 유역", "목지국 병합"],
  },
  {
    slug: "samguk-313-낙랑축출",
    era: "samguk",
    year: 313,
    title: "낙랑군 축출",
    kind: "war",
    period: "삼국-성립기",
    category: "대외관계",
    importance: 2,
    body: "고구려 미천왕이 낙랑군을 축출하여 대동강 유역을 확보하고 중국 세력을 한반도에서 몰아냈다.",
    keywords: ["미천왕", "낙랑군 축출", "대동강", "서안평 공격"],
  },
  {
    slug: "samguk-372-고구려불교",
    era: "samguk",
    year: 372,
    title: "고구려 불교 수용·태학",
    kind: "event",
    period: "삼국-전성기",
    category: "문화",
    importance: 3,
    body: "소수림왕 때 전진의 순도가 불교를 전하였고, 태학 설립·율령 반포로 중앙집권을 강화하였다.",
    keywords: ["소수림왕", "불교 수용", "순도", "전진", "태학", "율령 반포", "중앙집권"],
    relatedTo: ["고구려 불교 수용"],
  },
  {
    slug: "samguk-371-근초고왕",
    era: "samguk",
    year: 371,
    title: "백제 근초고왕 전성기",
    kind: "person",
    period: "삼국-전성기",
    category: "정치",
    importance: 3,
    body: "근초고왕이 마한을 정복하고 고구려 평양성을 공격해 고국원왕을 전사시켰으며, 요서·왜와 교류하고 칠지도를 전하였다.",
    keywords: ["근초고왕", "마한 정복", "평양성 공격", "고국원왕 전사", "칠지도", "왜", "요서 진출", "부자 상속", "고흥 서기"],
  },
  {
    slug: "samguk-384-백제불교",
    era: "samguk",
    year: 384,
    title: "백제 불교 수용",
    kind: "event",
    period: "삼국-전성기",
    category: "문화",
    importance: 2,
    body: "침류왕 때 동진의 마라난타가 불교를 전하여 백제가 불교를 공인하였다.",
    keywords: ["침류왕", "마라난타", "동진", "백제 불교"],
    relatedTo: ["백제 불교 수용"],
  },
  {
    slug: "samguk-391-광개토대왕",
    era: "samguk",
    year: 391,
    title: "광개토 대왕 즉위",
    kind: "person",
    period: "삼국-전성기",
    category: "대외관계",
    importance: 3,
    body: "영락 연호를 사용하며 만주와 한강 이북으로 영토를 넓혔고, 신라의 요청으로 왜를 격퇴하였다.",
    keywords: ["광개토 대왕", "영락", "연호", "만주", "신라 구원", "왜 격퇴", "후연", "광개토 대왕릉비"],
    relatedTo: ["광개토 대왕 즉위", "장수왕 평양 천도"],
  },
  {
    slug: "samguk-427-장수왕천도",
    era: "samguk",
    year: 427,
    title: "장수왕 평양 천도·남진",
    kind: "event",
    period: "삼국-전성기",
    category: "정치",
    importance: 3,
    body: "장수왕이 평양으로 천도하고 남진 정책을 추진해 475년 백제 한성을 함락하고 개로왕을 전사시켰다.",
    keywords: ["장수왕", "평양 천도", "남진 정책", "한성 함락", "개로왕 전사", "충주 고구려비", "광개토 대왕릉비"],
    relatedTo: ["장수왕 평양 천도"],
  },
  {
    slug: "samguk-475-웅진천도",
    era: "samguk",
    year: 475,
    title: "백제 웅진 천도",
    kind: "event",
    period: "삼국-항쟁기",
    category: "정치",
    importance: 2,
    body: "고구려의 공격으로 한성이 함락되자 문주왕이 웅진(공주)으로 천도하며 백제는 일시 쇠퇴하였다.",
    keywords: ["문주왕", "웅진 천도", "공주", "한성 함락", "백제 중흥"],
  },
  {
    slug: "samguk-520-법흥왕율령",
    era: "samguk",
    year: 520,
    title: "신라 법흥왕 율령 반포",
    kind: "system",
    period: "삼국-전성기",
    category: "정치",
    importance: 3,
    body: "법흥왕이 율령을 반포하고 병부 설치, 골품제 정비, 상대등 설치, 금관가야 병합, 건원 연호를 사용하였다.",
    keywords: ["법흥왕", "율령 반포", "병부", "골품제", "상대등", "금관가야 병합", "건원", "연호", "공복 제정"],
  },
  {
    slug: "samguk-527-신라불교",
    era: "samguk",
    year: 527,
    title: "신라 불교 공인",
    kind: "event",
    period: "삼국-전성기",
    category: "문화",
    importance: 3,
    body: "법흥왕 때 이차돈의 순교를 계기로 신라가 불교를 공인하였다.",
    keywords: ["법흥왕", "이차돈", "순교", "신라 불교 공인"],
    relatedTo: ["신라 불교 공인"],
  },
  {
    slug: "samguk-538-사비천도",
    era: "samguk",
    year: 538,
    title: "백제 성왕 사비 천도",
    kind: "event",
    period: "삼국-전성기",
    category: "정치",
    importance: 2,
    body: "성왕이 사비(부여)로 천도하고 국호를 남부여로 고치며 중흥을 꾀하였고, 일본에 불교를 전하였다.",
    keywords: ["성왕", "사비 천도", "부여", "남부여", "22부", "불교 전파", "노리사치계", "관산성 전투"],
    relatedTo: ["백제 멸망"],
  },
  {
    slug: "samguk-551-진흥왕한강",
    era: "samguk",
    year: 551,
    title: "신라 진흥왕 한강 유역 확보",
    kind: "person",
    period: "삼국-전성기",
    category: "대외관계",
    importance: 3,
    body: "진흥왕이 한강 유역을 차지하고 대가야를 정복하였으며, 화랑도 개편과 순수비(북한산비 등)를 세웠다.",
    keywords: ["진흥왕", "한강 유역", "대가야 정복", "화랑도", "순수비", "북한산비", "황초령비", "마운령비", "단양 적성비", "개국", "황룡사"],
  },
  {
    slug: "samguk-612-살수대첩",
    era: "samguk",
    year: 612,
    title: "살수 대첩",
    kind: "war",
    period: "삼국-항쟁기",
    category: "대외관계",
    importance: 3,
    body: "을지문덕이 수 양제의 113만 대군을 살수에서 크게 무찔러 고구려가 수의 침입을 격퇴하였다.",
    keywords: ["을지문덕", "살수 대첩", "수 양제", "살수", "여수 전쟁", "수나라"],
    relatedTo: ["안시성 싸움"],
  },
  {
    slug: "samguk-645-안시성",
    era: "samguk",
    year: 645,
    title: "안시성 싸움",
    kind: "war",
    period: "삼국-항쟁기",
    category: "대외관계",
    importance: 3,
    body: "당 태종의 침입을 안시성에서 격퇴하였다. 앞서 연개소문이 정변으로 권력을 장악하고 천리장성을 쌓아 대비하였다.",
    keywords: ["안시성", "당 태종", "연개소문", "천리장성", "여당 전쟁", "양만춘"],
    relatedTo: ["살수 대첩"],
  },
  {
    slug: "samguk-660-백제멸망",
    era: "samguk",
    year: 660,
    title: "백제 멸망",
    kind: "war",
    period: "삼국-멸망기",
    category: "대외관계",
    importance: 3,
    body: "나당 연합군의 공격으로 황산벌 전투(계백) 패배 후 사비성이 함락되어 백제가 멸망하였다.",
    keywords: ["백제 멸망", "나당 연합군", "황산벌 전투", "계백", "의자왕", "사비성", "김유신", "백제 부흥 운동"],
    relatedTo: ["성왕 사비 천도", "고구려 멸망"],
  },
  {
    slug: "samguk-668-고구려멸망",
    era: "samguk",
    year: 668,
    title: "고구려 멸망",
    kind: "war",
    period: "삼국-멸망기",
    category: "대외관계",
    importance: 3,
    body: "나당 연합군에 의해 평양성이 함락되어 고구려가 멸망하였고, 이후 검모잠 등이 부흥 운동을 전개하였다.",
    keywords: ["고구려 멸망", "평양성", "나당 연합군", "보장왕", "고구려 부흥 운동", "검모잠", "안승"],
    relatedTo: ["백제 멸망", "신라 삼국 통일"],
  },

  // ==================== 남북국 시대 (nambukguk) ====================
  {
    slug: "nambukguk-676-삼국통일",
    era: "nambukguk",
    year: 676,
    title: "신라 삼국 통일",
    kind: "war",
    period: "남북국-통일신라",
    category: "대외관계",
    importance: 3,
    body: "문무왕 때 매소성·기벌포 전투에서 당군을 물리치고 나당 전쟁에서 승리하여 삼국 통일을 완성하였다.",
    keywords: ["문무왕", "삼국 통일", "매소성 전투", "기벌포 전투", "나당 전쟁", "당 축출"],
    relatedTo: ["고구려 멸망", "신문왕 개혁"],
  },
  {
    slug: "nambukguk-682-신문왕",
    era: "nambukguk",
    year: 682,
    title: "신문왕 왕권 강화",
    kind: "person",
    period: "남북국-통일신라",
    category: "정치",
    importance: 3,
    body: "9주 5소경 정비, 9서당 10정, 국학 설립, 관료전 지급과 녹읍 폐지로 진골 귀족을 누르고 왕권을 강화하였다.",
    keywords: ["신문왕", "9주 5소경", "9서당 10정", "국학", "관료전", "녹읍 폐지", "김흠돌의 난", "만파식적"],
    relatedTo: ["신라 삼국 통일"],
  },
  {
    slug: "nambukguk-698-발해건국",
    era: "nambukguk",
    year: 698,
    title: "발해 건국",
    kind: "event",
    period: "남북국-발해",
    category: "정치",
    importance: 3,
    body: "대조영이 동모산에서 발해를 건국하며 고구려 계승 의식을 표방하였고, 고왕(천통) 연호를 사용하였다.",
    keywords: ["대조영", "발해", "동모산", "고구려 계승", "고왕", "천통", "진국", "말갈"],
    relatedTo: ["발해 문왕 체제 정비"],
  },
  {
    slug: "nambukguk-719-무왕",
    era: "nambukguk",
    year: 719,
    title: "발해 무왕 영토 확장",
    kind: "person",
    period: "남북국-발해",
    category: "대외관계",
    importance: 2,
    body: "무왕(인안)이 영토를 확장하고 장문휴를 보내 당의 산둥 지방(등주)을 공격하였으며 일본과 교류하였다.",
    keywords: ["무왕", "인안", "장문휴", "등주 공격", "산둥", "발해 일본 교류"],
  },
  {
    slug: "nambukguk-737-문왕",
    era: "nambukguk",
    year: 737,
    title: "발해 문왕 체제 정비",
    kind: "person",
    period: "남북국-발해",
    category: "정치",
    importance: 2,
    body: "문왕(대흥)이 상경 천도, 3성 6부 정비, 주자감 설치, 신라도 개설 등으로 체제를 정비하였다.",
    keywords: ["문왕", "대흥", "상경 천도", "3성 6부", "주자감", "신라도", "당과 친선"],
    relatedTo: ["발해 건국"],
  },
  {
    slug: "nambukguk-722-정전",
    era: "nambukguk",
    year: 722,
    title: "성덕왕 정전 지급",
    kind: "system",
    period: "남북국-통일신라",
    category: "경제",
    importance: 2,
    body: "성덕왕이 백성에게 정전을 지급하여 토지 지배를 강화하고 조세 수취 기반을 마련하였다.",
    keywords: ["성덕왕", "정전", "토지 지급", "민정 문서", "촌락 문서"],
  },
  {
    slug: "nambukguk-751-불국사",
    era: "nambukguk",
    year: 751,
    title: "불국사·석굴암 창건",
    kind: "culture",
    period: "남북국-통일신라",
    category: "문화",
    importance: 3,
    body: "경덕왕 때 김대성이 불국사와 석굴암을 창건하여 통일 신라 불교 예술의 정수를 보여준다.",
    keywords: ["불국사", "석굴암", "김대성", "경덕왕", "다보탑", "석가탑", "무구정광대다라니경", "불교 예술"],
  },
  {
    slug: "nambukguk-788-독서삼품과",
    era: "nambukguk",
    year: 788,
    title: "독서삼품과 실시",
    kind: "system",
    period: "남북국-통일신라",
    category: "정치",
    importance: 2,
    body: "원성왕이 유교 경전 이해 수준으로 관리를 채용하는 독서삼품과를 실시하였으나 진골의 반발로 한계가 있었다.",
    keywords: ["원성왕", "독서삼품과", "유교 경전", "관리 채용", "국학"],
  },
  {
    slug: "nambukguk-822-김헌창",
    era: "nambukguk",
    year: 822,
    title: "김헌창의 난",
    kind: "event",
    period: "남북국-신라말기",
    category: "정치",
    importance: 1,
    body: "웅천주 도독 김헌창이 아버지 김주원이 왕이 되지 못한 것에 불만을 품고 난을 일으켰다(국호 장안).",
    keywords: ["김헌창", "김헌창의 난", "웅천주", "장안", "진골 귀족 분열", "왕위 쟁탈전"],
  },
  {
    slug: "nambukguk-828-청해진",
    era: "nambukguk",
    year: 828,
    title: "청해진 설치",
    kind: "person",
    period: "남북국-신라말기",
    category: "경제",
    importance: 2,
    body: "장보고가 완도에 청해진을 세워 해적을 소탕하고 당·신라·일본을 잇는 해상 무역을 장악하였다.",
    keywords: ["장보고", "청해진", "완도", "해상 무역", "법화원", "해적 소탕"],
  },
  {
    slug: "nambukguk-889-원종애노",
    era: "nambukguk",
    year: 889,
    title: "원종·애노의 난",
    kind: "event",
    period: "남북국-신라말기",
    category: "사회",
    importance: 2,
    body: "진성여왕 때 과도한 수취에 항거해 사벌주에서 원종·애노가 봉기, 전국적 농민 봉기와 호족 성장의 계기가 되었다.",
    keywords: ["원종", "애노", "진성여왕", "사벌주", "농민 봉기", "호족", "6두품", "최치원 시무 10조"],
  },
  {
    slug: "nambukguk-900-후백제",
    era: "nambukguk",
    year: 900,
    title: "후백제 건국",
    kind: "event",
    period: "남북국-후삼국",
    category: "정치",
    importance: 2,
    body: "견훤이 완산주(전주)에 후백제를 세우고 중국과 외교하였으며, 후삼국 시대가 본격화되었다.",
    keywords: ["견훤", "후백제", "완산주", "전주", "후삼국", "신라 경애왕 살해"],
  },
  {
    slug: "nambukguk-901-후고구려",
    era: "nambukguk",
    year: 901,
    title: "후고구려 건국",
    kind: "event",
    period: "남북국-후삼국",
    category: "정치",
    importance: 2,
    body: "궁예가 송악에서 후고구려를 세우고 국호를 마진·태봉으로 바꾸며 광평성 등 관제를 정비하였다.",
    keywords: ["궁예", "후고구려", "송악", "마진", "태봉", "광평성", "철원 천도", "미륵 신앙"],
  },
  {
    slug: "nambukguk-926-발해멸망",
    era: "nambukguk",
    year: 926,
    title: "발해 멸망",
    kind: "war",
    period: "남북국-발해",
    category: "대외관계",
    importance: 2,
    body: "거란(요)의 침입으로 발해가 멸망하였고, 이후 발해 유민이 고려로 망명하였다.",
    keywords: ["발해 멸망", "거란", "요", "발해 유민", "고려 망명", "해동성국"],
  },

  // ==================== 고려 시대 (goryeo) ====================
  {
    slug: "goryeo-918-건국",
    era: "goryeo",
    year: 918,
    title: "고려 건국",
    kind: "event",
    period: "고려-초기",
    category: "정치",
    importance: 3,
    body: "왕건(태조)이 궁예를 몰아내고 송악(개경)을 도읍으로 고려를 건국하였다.",
    keywords: ["왕건", "태조", "고려 건국", "송악", "개경", "궁예 축출", "후삼국"],
    relatedTo: ["후삼국 통일"],
  },
  {
    slug: "goryeo-936-후삼국통일",
    era: "goryeo",
    year: 936,
    title: "후삼국 통일",
    kind: "war",
    period: "고려-초기",
    category: "정치",
    importance: 3,
    body: "고려가 신라의 항복(935)과 일리천 전투에서 후백제를 정벌하여 후삼국을 통일하였다. 태조는 훈요 10조·기인·사심관 제도를 시행하였다.",
    keywords: ["후삼국 통일", "일리천 전투", "신라 항복", "경순왕", "훈요 10조", "기인 제도", "사심관 제도", "북진 정책", "흑창", "정계", "계백료서"],
    relatedTo: ["고려 건국"],
  },
  {
    slug: "goryeo-956-노비안검법",
    era: "goryeo",
    year: 956,
    title: "노비안검법",
    kind: "system",
    period: "고려-초기",
    category: "사회",
    importance: 3,
    body: "광종이 불법으로 노비가 된 자를 해방하여 호족의 경제·군사 기반을 약화시키고 국가 재정을 확충하였다.",
    keywords: ["광종", "노비안검법", "호족 약화", "왕권 강화"],
    relatedTo: ["과거제 시행"],
  },
  {
    slug: "goryeo-958-과거제",
    era: "goryeo",
    year: 958,
    title: "과거제 시행",
    kind: "system",
    period: "고려-초기",
    category: "정치",
    importance: 3,
    body: "광종이 쌍기의 건의로 과거제를 처음 시행하고 백관의 공복을 제정하였으며 광덕·준풍 연호를 사용하였다.",
    keywords: ["광종", "과거제", "쌍기", "공복 제정", "광덕", "준풍", "연호", "제위보", "황제 칭호"],
    relatedTo: ["노비안검법"],
  },
  {
    slug: "goryeo-982-시무28조",
    era: "goryeo",
    year: 982,
    title: "최승로 시무 28조",
    kind: "system",
    period: "고려-초기",
    category: "정치",
    importance: 3,
    body: "최승로가 성종에게 올린 개혁안으로, 유교 정치 이념과 12목 설치·지방관 파견의 바탕이 되었다.",
    keywords: ["최승로", "시무 28조", "성종", "유교 정치", "12목", "지방관 파견", "국자감", "향리 제도"],
  },
  {
    slug: "goryeo-993-서희담판",
    era: "goryeo",
    year: 993,
    title: "서희의 외교 담판",
    kind: "person",
    period: "고려-초기",
    category: "대외관계",
    importance: 3,
    body: "거란의 1차 침입 때 서희가 소손녕과 외교 담판을 벌여 강동 6주를 확보하였다.",
    keywords: ["서희", "외교 담판", "거란 1차 침입", "소손녕", "강동 6주", "송 단교"],
    relatedTo: ["귀주 대첩"],
  },
  {
    slug: "goryeo-1019-귀주대첩",
    era: "goryeo",
    year: 1019,
    title: "귀주 대첩",
    kind: "war",
    period: "고려-초기",
    category: "대외관계",
    importance: 3,
    body: "거란의 3차 침입 때 강감찬이 귀주에서 거란군을 크게 무찔렀고, 이후 천리장성·나성을 축조하였다.",
    keywords: ["강감찬", "귀주 대첩", "거란 3차 침입", "천리장성", "개경 나성", "초조대장경"],
    relatedTo: ["서희의 외교 담판"],
  },
  {
    slug: "goryeo-1107-윤관여진",
    era: "goryeo",
    year: 1107,
    title: "윤관 동북 9성 축조",
    kind: "war",
    period: "고려-문벌귀족기",
    category: "대외관계",
    importance: 2,
    body: "예종 때 윤관이 별무반을 이끌고 여진을 정벌하여 동북 9성을 쌓았으나 이후 여진에 반환하였다.",
    keywords: ["윤관", "별무반", "여진 정벌", "동북 9성", "예종", "신기군", "신보군", "항마군"],
  },
  {
    slug: "goryeo-1126-이자겸",
    era: "goryeo",
    year: 1126,
    title: "이자겸의 난",
    kind: "event",
    period: "고려-문벌귀족기",
    category: "정치",
    importance: 2,
    body: "외척 이자겸이 척준경과 함께 권력을 독점하려다 난을 일으켰으나 실패하여 문벌 귀족 사회의 동요를 드러냈다.",
    keywords: ["이자겸", "이자겸의 난", "척준경", "인종", "외척", "문벌 귀족"],
  },
  {
    slug: "goryeo-1135-묘청",
    era: "goryeo",
    year: 1135,
    title: "묘청의 서경 천도 운동",
    kind: "event",
    period: "고려-문벌귀족기",
    category: "정치",
    importance: 3,
    body: "묘청 등이 서경 천도와 칭제건원·금국 정벌을 주장하며 난을 일으켰으나 김부식에게 진압되었다.",
    keywords: ["묘청", "서경 천도", "칭제건원", "금국 정벌", "김부식", "대위국", "삼국사기"],
  },
  {
    slug: "goryeo-1145-삼국사기",
    era: "goryeo",
    year: 1145,
    title: "삼국사기 편찬",
    kind: "culture",
    period: "고려-문벌귀족기",
    category: "문화",
    importance: 2,
    body: "김부식이 인종의 명으로 현존 최고(最古)의 역사서인 삼국사기를 기전체로 편찬하였다.",
    keywords: ["김부식", "삼국사기", "기전체", "현존 최고 역사서", "인종", "유교 사관"],
  },
  {
    slug: "goryeo-1170-무신정변",
    era: "goryeo",
    year: 1170,
    title: "무신정변",
    kind: "event",
    period: "고려-무신정권기",
    category: "정치",
    importance: 3,
    body: "정중부·이의방 등 무신들이 차별에 반발해 정변을 일으켜 권력을 장악, 중방 중심의 무신 정권이 시작되었다.",
    keywords: ["무신정변", "정중부", "이의방", "이고", "중방", "무신 정권", "보현원"],
    relatedTo: ["만적의 난"],
  },
  {
    slug: "goryeo-1176-망이망소이",
    era: "goryeo",
    year: 1176,
    title: "망이·망소이의 난",
    kind: "event",
    period: "고려-무신정권기",
    category: "사회",
    importance: 2,
    body: "공주 명학소에서 망이·망소이가 신분 차별에 항거해 봉기, 무신 집권기 하층민 봉기의 대표 사례이다.",
    keywords: ["망이", "망소이", "명학소", "공주", "하층민 봉기", "특수 행정 구역"],
  },
  {
    slug: "goryeo-1196-최충헌",
    era: "goryeo",
    year: 1196,
    title: "최충헌 집권",
    kind: "person",
    period: "고려-무신정권기",
    category: "정치",
    importance: 2,
    body: "최충헌이 권력을 잡아 교정도감을 설치하고 봉사 10조를 올렸으며, 4대 60여 년의 최씨 무신 정권을 열었다.",
    keywords: ["최충헌", "교정도감", "봉사 10조", "최씨 정권", "도방", "삼별초"],
  },
  {
    slug: "goryeo-1198-만적의난",
    era: "goryeo",
    year: 1198,
    title: "만적의 난",
    kind: "event",
    period: "고려-무신정권기",
    category: "사회",
    importance: 2,
    body: "최충헌의 사노 만적이 개경에서 신분 해방을 도모한 봉기를 계획하였으나 사전에 발각되었다.",
    keywords: ["만적", "만적의 난", "최충헌", "노비 봉기", "신분 해방"],
    relatedTo: ["무신정변"],
  },
  {
    slug: "goryeo-1231-몽골침입",
    era: "goryeo",
    year: 1231,
    title: "몽골 침입·강화 천도",
    kind: "war",
    period: "고려-무신정권기",
    category: "대외관계",
    importance: 3,
    body: "몽골의 1차 침입 후 최우가 1232년 강화도로 천도하여 장기 항전을 시작하였고, 처인성에서 김윤후가 살리타를 사살하였다.",
    keywords: ["몽골 침입", "강화 천도", "최우", "처인성 전투", "김윤후", "살리타", "초조대장경 소실", "황룡사 9층 목탑 소실"],
    relatedTo: ["팔만대장경 조판", "삼별초 항쟁"],
  },
  {
    slug: "goryeo-1236-팔만대장경",
    era: "goryeo",
    year: 1236,
    title: "팔만대장경 조판",
    kind: "culture",
    period: "고려-무신정권기",
    category: "문화",
    importance: 3,
    body: "몽골 침입을 부처의 힘으로 막고자 강화도에서 재조대장경(팔만대장경)을 제작하였으며, 현재 합천 해인사 장경판전에 보관되어 있다.",
    keywords: ["팔만대장경", "재조대장경", "강화도", "해인사", "장경판전", "몽골 침입", "대장도감"],
    relatedTo: ["몽골 침입·강화 천도"],
  },
  {
    slug: "goryeo-1270-삼별초",
    era: "goryeo",
    year: 1270,
    title: "개경 환도·삼별초 항쟁",
    kind: "war",
    period: "고려-원간섭기",
    category: "대외관계",
    importance: 2,
    body: "무신 정권이 무너지고 개경으로 환도하자 삼별초가 강화도·진도·제주도로 옮겨 가며 대몽 항쟁을 이어갔다.",
    keywords: ["삼별초", "개경 환도", "배중손", "진도", "용장성", "제주도", "항파두리", "대몽 항쟁", "여몽 연합군"],
    relatedTo: ["몽골 침입·강화 천도"],
  },
  {
    slug: "goryeo-1274-일본원정",
    era: "goryeo",
    year: 1274,
    title: "여원 연합군 일본 원정",
    kind: "war",
    period: "고려-원간섭기",
    category: "대외관계",
    importance: 1,
    body: "원의 강요로 고려가 두 차례(1274, 1281) 일본 원정에 동원되었으나 태풍 등으로 실패하였고, 정동행성이 설치되었다.",
    keywords: ["일본 원정", "여원 연합군", "정동행성", "원 간섭", "충렬왕"],
  },
  {
    slug: "goryeo-1287-삼국유사",
    era: "goryeo",
    year: 1287,
    title: "삼국유사·제왕운기",
    kind: "culture",
    period: "고려-원간섭기",
    category: "문화",
    importance: 2,
    body: "일연이 삼국유사를 지어 단군 신화를 수록하였고, 이승휴가 제왕운기를 편찬하여 자주적 역사 의식을 보였다.",
    keywords: ["일연", "삼국유사", "단군 신화", "이승휴", "제왕운기", "자주적 역사관", "원 간섭기"],
  },
  {
    slug: "goryeo-1351-공민왕",
    era: "goryeo",
    year: 1351,
    title: "공민왕 반원 개혁",
    kind: "person",
    period: "고려-말기",
    category: "정치",
    importance: 3,
    body: "공민왕이 쌍성총관부 수복, 정동행성 이문소 폐지, 친원파 기철 제거, 전민변정도감(신돈) 설치로 반원 자주 개혁을 추진하였다.",
    keywords: ["공민왕", "반원 자주", "쌍성총관부", "정동행성 이문소", "기철", "전민변정도감", "신돈", "정방 폐지", "변발 금지"],
  },
  {
    slug: "goryeo-1359-홍건적",
    era: "goryeo",
    year: 1359,
    title: "홍건적·왜구 침입",
    kind: "war",
    period: "고려-말기",
    category: "대외관계",
    importance: 2,
    body: "원 말 혼란기에 홍건적과 왜구가 침입하여 최영·이성계 등 신흥 무인 세력이 격퇴하며 성장하였다.",
    keywords: ["홍건적", "왜구", "최영", "이성계", "황산 대첩", "진포 대첩", "최무선", "화통도감", "신흥 무인"],
  },
  {
    slug: "goryeo-1377-직지심체요절",
    era: "goryeo",
    year: 1377,
    title: "직지심체요절",
    kind: "culture",
    period: "고려-말기",
    category: "문화",
    importance: 3,
    body: "청주 흥덕사에서 간행된 현존 세계 최고(最古)의 금속 활자본으로, 현재 프랑스 국립도서관에 소장되어 있다.",
    keywords: ["직지심체요절", "흥덕사", "청주", "금속 활자", "현존 최고 금속활자본", "프랑스 국립도서관"],
    relatedTo: ["팔만대장경 조판"],
  },
  {
    slug: "goryeo-1388-위화도회군",
    era: "goryeo",
    year: 1388,
    title: "위화도 회군",
    kind: "event",
    period: "고려-말기",
    category: "정치",
    importance: 3,
    body: "이성계가 요동 정벌에 반대해 4불가론을 내세우고 위화도에서 회군하여 권력을 장악, 조선 건국의 발판이 되었다.",
    keywords: ["이성계", "위화도 회군", "요동 정벌", "4불가론", "최영 제거", "신진 사대부"],
    relatedTo: ["과전법", "조선 건국"],
  },
  {
    slug: "goryeo-1391-과전법",
    era: "goryeo",
    year: 1391,
    title: "과전법 시행",
    kind: "system",
    period: "고려-말기",
    category: "경제",
    importance: 2,
    body: "조준 등의 건의로 과전법을 실시해 신진 사대부의 경제 기반을 마련하고 권문세족의 농장을 혁파하였다.",
    keywords: ["과전법", "조준", "신진 사대부", "권문세족", "전시과 폐지", "토지 개혁"],
    relatedTo: ["위화도 회군"],
  },

  // ==================== 조선 시대 (joseon) ====================
  {
    slug: "joseon-1392-건국",
    era: "joseon",
    year: 1392,
    title: "조선 건국",
    kind: "event",
    period: "조선-전기",
    category: "정치",
    importance: 3,
    body: "이성계가 정도전 등 신진 사대부와 함께 조선을 건국하고 1394년 한양으로 천도하였다.",
    keywords: ["이성계", "태조", "조선 건국", "정도전", "한양 천도", "경복궁", "조선경국전", "재상 중심"],
    relatedTo: ["위화도 회군"],
  },
  {
    slug: "joseon-1400-태종",
    era: "joseon",
    year: 1400,
    title: "태종 왕권 강화",
    kind: "person",
    period: "조선-전기",
    category: "정치",
    importance: 2,
    body: "태종이 두 차례 왕자의 난을 거쳐 즉위, 6조 직계제·사병 혁파·호패법·신문고를 시행하여 왕권을 강화하였다.",
    keywords: ["태종", "이방원", "왕자의 난", "6조 직계제", "사병 혁파", "호패법", "신문고", "8도 정비"],
  },
  {
    slug: "joseon-1418-세종",
    era: "joseon",
    year: 1418,
    title: "세종 즉위",
    kind: "person",
    period: "조선-전기",
    category: "정치",
    importance: 2,
    body: "세종이 집현전을 설치하고 의정부 서사제를 시행했으며, 4군 6진 개척, 공법(전분6등·연분9등) 등을 마련하였다.",
    keywords: ["세종", "집현전", "의정부 서사제", "4군 6진", "최윤덕", "김종서", "공법", "전분6등법", "연분9등법", "측우기", "칠정산", "농사직설", "갑인자"],
  },
  {
    slug: "joseon-1446-훈민정음",
    era: "joseon",
    year: 1446,
    title: "훈민정음 반포",
    kind: "culture",
    period: "조선-전기",
    category: "문화",
    importance: 3,
    body: "세종이 집현전 학자들과 훈민정음을 창제(1443)·반포(1446)하여 백성이 쉽게 글을 익히도록 하였다.",
    keywords: ["세종", "훈민정음", "한글 창제", "집현전", "용비어천가", "백성"],
    relatedTo: ["조선 건국"],
  },
  {
    slug: "joseon-1485-경국대전",
    era: "joseon",
    year: 1485,
    title: "경국대전 완성",
    kind: "system",
    period: "조선-전기",
    category: "정치",
    importance: 3,
    body: "세조 때 편찬을 시작해 성종 때 완성·반포된 조선의 기본 법전으로, 유교적 통치 질서를 확립하였다.",
    keywords: ["경국대전", "성종", "세조", "법전", "유교 통치", "6전 체제", "홍문관", "사림 등용"],
    relatedTo: ["훈민정음 반포"],
  },
  {
    slug: "joseon-1498-무오사화",
    era: "joseon",
    year: 1498,
    title: "무오사화",
    kind: "event",
    period: "조선-사림기",
    category: "정치",
    importance: 2,
    body: "연산군 때 김종직의 조의제문을 빌미로 훈구파가 사림을 축출한 첫 사화이다.",
    keywords: ["무오사화", "연산군", "김종직", "조의제문", "훈구파", "사림", "김일손"],
    relatedTo: ["기묘사화"],
  },
  {
    slug: "joseon-1504-갑자사화",
    era: "joseon",
    year: 1504,
    title: "갑자사화",
    kind: "event",
    period: "조선-사림기",
    category: "정치",
    importance: 1,
    body: "연산군이 생모 폐비 윤씨 사건을 빌미로 훈구·사림 세력을 대거 숙청하였다.",
    keywords: ["갑자사화", "연산군", "폐비 윤씨", "훈구", "사림 숙청"],
  },
  {
    slug: "joseon-1519-기묘사화",
    era: "joseon",
    year: 1519,
    title: "기묘사화",
    kind: "event",
    period: "조선-사림기",
    category: "정치",
    importance: 2,
    body: "중종 때 조광조의 급진 개혁(현량과·위훈 삭제·소격서 폐지)에 반발한 훈구파가 사림을 제거하였다.",
    keywords: ["기묘사화", "중종", "조광조", "현량과", "위훈 삭제", "소격서 폐지", "주초위왕", "훈구파"],
    relatedTo: ["무오사화"],
  },
  {
    slug: "joseon-1543-백운동서원",
    era: "joseon",
    year: 1543,
    title: "백운동 서원 건립",
    kind: "culture",
    period: "조선-사림기",
    category: "문화",
    importance: 2,
    body: "주세붕이 안향을 기리는 최초의 서원인 백운동 서원을 세웠고, 이후 소수 서원으로 사액되어 사림의 기반이 되었다.",
    keywords: ["백운동 서원", "주세붕", "안향", "소수 서원", "사액 서원", "사림", "성리학"],
  },
  {
    slug: "joseon-1575-붕당",
    era: "joseon",
    year: 1575,
    title: "붕당 정치 시작",
    kind: "system",
    period: "조선-사림기",
    category: "정치",
    importance: 2,
    body: "선조 때 이조 전랑 임명 문제로 사림이 동인과 서인으로 나뉘면서 붕당 정치가 시작되었다.",
    keywords: ["붕당", "동인", "서인", "이조 전랑", "선조", "김효원", "심의겸", "사림 분화"],
  },
  {
    slug: "joseon-1592-임진왜란",
    era: "joseon",
    year: 1592,
    title: "임진왜란",
    kind: "war",
    period: "조선-양난기",
    category: "대외관계",
    importance: 3,
    body: "일본의 침략으로 시작된 전쟁으로, 이순신의 수군(한산도 대첩)과 곽재우 등 의병, 명군의 참전으로 극복하였다.",
    keywords: ["임진왜란", "이순신", "한산도 대첩", "거북선", "곽재우", "의병", "권율", "행주 대첩", "김시민", "진주 대첩", "명군", "선조"],
    relatedTo: ["병자호란"],
  },
  {
    slug: "joseon-1608-대동법",
    era: "joseon",
    year: 1608,
    title: "대동법 실시",
    kind: "system",
    period: "조선-후기",
    category: "경제",
    importance: 3,
    body: "광해군 때 경기도에서 처음 시행, 공납을 토지 결수 기준 쌀(대동미)로 바꾸어 농민 부담을 덜고 공인이 등장하였다.",
    keywords: ["대동법", "광해군", "경기도", "공납", "대동미", "공인", "선혜청", "이원익", "상품 화폐 경제"],
    relatedTo: ["임진왜란"],
  },
  {
    slug: "joseon-1623-인조반정",
    era: "joseon",
    year: 1623,
    title: "인조반정",
    kind: "event",
    period: "조선-양난기",
    category: "정치",
    importance: 2,
    body: "서인이 광해군의 중립 외교와 폐모살제를 명분으로 반정을 일으켜 인조를 옹립하고 친명배금 정책을 폈다.",
    keywords: ["인조반정", "광해군", "서인", "인조", "중립 외교", "친명배금", "폐모살제"],
  },
  {
    slug: "joseon-1636-병자호란",
    era: "joseon",
    year: 1636,
    title: "병자호란",
    kind: "war",
    period: "조선-양난기",
    category: "대외관계",
    importance: 3,
    body: "청의 침입으로 인조가 남한산성에서 항전하다 삼전도에서 굴욕적으로 항복하였고, 이후 북벌론이 대두하였다.",
    keywords: ["병자호란", "인조", "남한산성", "삼전도", "삼전도비", "청", "북벌론", "효종", "주화론", "척화론", "소현세자"],
    relatedTo: ["임진왜란"],
  },
  {
    slug: "joseon-1678-상평통보",
    era: "joseon",
    year: 1678,
    title: "상평통보 유통",
    kind: "system",
    period: "조선-후기",
    category: "경제",
    importance: 2,
    body: "숙종 때 상평통보가 전국적으로 유통되어 상품 화폐 경제가 발달하였으나, 화폐를 쌓아두는 전황이 나타나기도 하였다.",
    keywords: ["상평통보", "숙종", "화폐", "상품 화폐 경제", "전황", "장시", "객주", "여각", "보부상"],
  },
  {
    slug: "joseon-1680-환국",
    era: "joseon",
    year: 1680,
    title: "숙종 환국 정치",
    kind: "event",
    period: "조선-후기",
    category: "정치",
    importance: 2,
    body: "숙종 때 경신·기사·갑술환국으로 집권 붕당이 급격히 교체되며 붕당 간 대립이 일당 전제화로 변질되었다.",
    keywords: ["숙종", "환국", "경신환국", "기사환국", "갑술환국", "남인", "서인", "노론", "소론", "일당 전제화"],
  },
  {
    slug: "joseon-1725-영조탕평",
    era: "joseon",
    year: 1725,
    title: "영조 탕평책",
    kind: "person",
    period: "조선-후기",
    category: "정치",
    importance: 3,
    body: "영조가 탕평책으로 붕당 갈등을 누르고 탕평비를 세웠으며, 균역법·신문고 부활·속대전 편찬을 시행하였다.",
    keywords: ["영조", "탕평책", "탕평비", "균역법", "속대전", "신문고 부활", "이인좌의 난", "서원 정리", "준론 탕평"],
    relatedTo: ["균역법"],
  },
  {
    slug: "joseon-1750-균역법",
    era: "joseon",
    year: 1750,
    title: "균역법 실시",
    kind: "system",
    period: "조선-후기",
    category: "경제",
    importance: 2,
    body: "영조가 군포 부담을 2필에서 1필로 줄이고 결작·선무군관포 등으로 부족분을 보충하여 백성의 부담을 덜었다.",
    keywords: ["균역법", "영조", "군포", "결작", "선무군관포", "어염세", "양인 부담 경감"],
    relatedTo: ["영조 탕평책"],
  },
  {
    slug: "joseon-1776-정조",
    era: "joseon",
    year: 1776,
    title: "정조 개혁 정치",
    kind: "person",
    period: "조선-후기",
    category: "정치",
    importance: 3,
    body: "정조가 규장각·초계문신제·장용영을 설치하고 신해통공으로 금난전권을 폐지하였으며 탕평을 계승하였다.",
    keywords: ["정조", "규장각", "초계문신", "장용영", "신해통공", "금난전권 폐지", "대전통편", "수원 화성", "준론 탕평"],
    relatedTo: ["수원 화성 완공"],
  },
  {
    slug: "joseon-1796-수원화성",
    era: "joseon",
    year: 1796,
    title: "수원 화성 완공",
    kind: "culture",
    period: "조선-후기",
    category: "문화",
    importance: 2,
    body: "정조가 정약용의 거중기를 활용해 수원 화성을 축조하고 정치·군사·상업의 중심지로 삼았다.",
    keywords: ["수원 화성", "정조", "정약용", "거중기", "화성성역의궤", "신도시", "유네스코"],
    relatedTo: ["정조 개혁 정치"],
  },
  {
    slug: "joseon-1610-동의보감",
    era: "joseon",
    year: 1610,
    title: "동의보감 완성",
    kind: "culture",
    period: "조선-후기",
    category: "문화",
    importance: 1,
    body: "허준이 우리 실정에 맞는 의서인 동의보감을 완성하였으며, 동아시아 의학 발전에 기여하고 유네스코 기록유산에 등재되었다.",
    keywords: ["허준", "동의보감", "의서", "광해군", "유네스코 기록유산", "전통 의학"],
  },
  {
    slug: "joseon-1750-실학",
    era: "joseon",
    year: 1750,
    title: "실학의 발달",
    kind: "culture",
    period: "조선-후기",
    category: "사회",
    importance: 2,
    body: "유형원·이익·정약용의 중농학파(토지 개혁)와 유수원·홍대용·박지원·박제가의 중상학파(상공업 진흥)가 사회 개혁을 모색하였다.",
    keywords: ["실학", "중농학파", "유형원", "이익", "정약용", "여전론", "목민심서", "중상학파", "북학파", "박지원", "열하일기", "박제가", "북학의", "홍대용", "유수원"],
  },
  {
    slug: "joseon-1860-동학창시",
    era: "joseon",
    year: 1860,
    title: "동학 창시",
    kind: "culture",
    period: "조선-세도정치기",
    category: "사회",
    importance: 2,
    body: "최제우가 인내천·후천개벽을 내세운 동학을 창시하였으나 혹세무민죄로 처형되었고, 최시형이 교리를 정리하여 교세를 확장하였다.",
    keywords: ["동학", "최제우", "인내천", "후천개벽", "보국안민", "최시형", "동경대전", "용담유사", "삼남 지방"],
    relatedTo: ["동학 농민 운동"],
  },
  {
    slug: "joseon-1801-신유박해",
    era: "joseon",
    year: 1801,
    title: "신유박해",
    kind: "event",
    period: "조선-세도정치기",
    category: "사회",
    importance: 1,
    body: "순조 즉위 후 세도 정권이 천주교를 탄압한 신유박해로 정약용 등이 유배되고 황사영 백서 사건이 일어났다.",
    keywords: ["신유박해", "순조", "천주교", "정약용 유배", "황사영 백서", "세도 정치"],
  },
  {
    slug: "joseon-1811-홍경래",
    era: "joseon",
    year: 1811,
    title: "홍경래의 난",
    kind: "event",
    period: "조선-세도정치기",
    category: "사회",
    importance: 2,
    body: "평안도 지역 차별과 세도 정치의 폐단에 항거해 홍경래가 봉기하였다.",
    keywords: ["홍경래", "홍경래의 난", "평안도 차별", "세도 정치", "정주성", "몰락 양반"],
    relatedTo: ["임술 농민 봉기"],
  },
  {
    slug: "joseon-1862-임술농민봉기",
    era: "joseon",
    year: 1862,
    title: "임술 농민 봉기",
    kind: "event",
    period: "조선-세도정치기",
    category: "사회",
    importance: 2,
    body: "삼정의 문란에 항거해 진주 민란(유계춘)을 시작으로 전국에서 농민 봉기가 일어나 삼정이정청이 설치되었다.",
    keywords: ["임술 농민 봉기", "진주 민란", "유계춘", "삼정의 문란", "전정", "군정", "환곡", "삼정이정청", "세도 정치"],
    relatedTo: ["홍경래의 난"],
  },

  // ==================== 근대 (modern) ====================
  {
    slug: "modern-1863-흥선대원군",
    era: "modern",
    year: 1863,
    title: "흥선대원군 집권",
    kind: "person",
    period: "근대-대원군집권기",
    category: "정치",
    importance: 3,
    body: "고종의 즉위로 집권한 흥선대원군이 서원 철폐·호포제·사창제·경복궁 중건과 통상 수교 거부를 추진하였다.",
    keywords: ["흥선대원군", "고종", "서원 철폐", "호포제", "사창제", "경복궁 중건", "당백전", "비변사 폐지", "통상 수교 거부", "대전회통"],
    relatedTo: ["강화도 조약"],
  },
  {
    slug: "modern-1866-병인양요",
    era: "modern",
    year: 1866,
    title: "병인양요",
    kind: "war",
    period: "근대-대원군집권기",
    category: "대외관계",
    importance: 2,
    body: "병인박해를 구실로 프랑스 함대가 강화도를 침략하였고, 양헌수·한성근이 격퇴하였으나 외규장각 의궤를 약탈당하였다.",
    keywords: ["병인양요", "병인박해", "프랑스", "강화도", "양헌수", "정족산성", "외규장각", "의궤 약탈", "천주교 탄압"],
  },
  {
    slug: "modern-1871-신미양요",
    era: "modern",
    year: 1871,
    title: "신미양요·척화비",
    kind: "war",
    period: "근대-대원군집권기",
    category: "대외관계",
    importance: 2,
    body: "제너럴셔먼호 사건을 구실로 미국 함대가 강화도를 침략, 어재연이 광성보에서 항전하였고 이후 척화비를 건립하였다.",
    keywords: ["신미양요", "제너럴셔먼호", "미국", "광성보", "어재연", "수자기", "척화비", "통상 수교 거부"],
  },
  {
    slug: "modern-1876-강화도조약",
    era: "modern",
    year: 1876,
    title: "강화도 조약",
    kind: "event",
    period: "근대-개항기",
    category: "대외관계",
    importance: 3,
    body: "운요호 사건을 계기로 체결된 최초의 근대적·불평등 조약으로, 부산·원산·인천 개항과 해안 측량권·치외법권을 규정하였다.",
    keywords: ["강화도 조약", "운요호 사건", "불평등 조약", "부산", "원산", "인천", "치외법권", "해안 측량권", "조일수호조규", "개항"],
    relatedTo: ["흥선대원군 집권", "갑신정변"],
  },
  {
    slug: "modern-1882-임오군란",
    era: "modern",
    year: 1882,
    title: "임오군란",
    kind: "event",
    period: "근대-개항기",
    category: "정치",
    importance: 2,
    body: "구식 군인에 대한 차별과 별기군 우대에 반발해 일어난 군란으로, 청군 개입과 제물포 조약·조청상민수륙무역장정 체결로 이어졌다.",
    keywords: ["임오군란", "구식 군인", "별기군", "흥선대원군 재집권", "청군 개입", "제물포 조약", "조청상민수륙무역장정", "민씨 정권"],
  },
  {
    slug: "modern-1884-갑신정변",
    era: "modern",
    year: 1884,
    title: "갑신정변",
    kind: "event",
    period: "근대-개항기",
    category: "정치",
    importance: 3,
    body: "김옥균 등 급진 개화파가 우정총국 개국 축하연을 이용해 정변을 일으켜 14개조 정강을 발표했으나 청군 개입으로 3일 만에 실패하였다.",
    keywords: ["갑신정변", "김옥균", "박영효", "급진 개화파", "우정총국", "14개조 정강", "청군 개입", "한성 조약", "톈진 조약", "3일 천하"],
    relatedTo: ["강화도 조약", "동학 농민 운동"],
  },
  {
    slug: "modern-1894-동학농민운동",
    era: "modern",
    year: 1894,
    title: "동학 농민 운동",
    kind: "event",
    period: "근대-개항기",
    category: "사회",
    importance: 3,
    body: "전봉준 등이 반봉건·반외세를 내걸고 봉기, 전주 화약과 집강소 설치를 거쳐 우금치 전투에서 패하였고 갑오개혁의 배경이 되었다.",
    keywords: ["동학 농민 운동", "전봉준", "고부 민란", "황토현 전투", "전주 화약", "집강소", "폐정 개혁안", "우금치 전투", "반봉건", "반외세", "녹두장군"],
    relatedTo: ["갑신정변", "갑오개혁"],
  },
  {
    slug: "modern-1894-갑오개혁",
    era: "modern",
    year: 1894,
    title: "갑오개혁",
    kind: "system",
    period: "근대-개항기",
    category: "정치",
    importance: 3,
    body: "군국기무처를 중심으로 신분제 폐지·과거제 폐지·재정 일원화 등 근대적 개혁을 추진하였고, 2차 개혁에서 홍범 14조를 반포하였다.",
    keywords: ["갑오개혁", "군국기무처", "신분제 폐지", "과거제 폐지", "탁지아문", "홍범 14조", "은본위제", "조혼 금지", "김홍집"],
    relatedTo: ["동학 농민 운동"],
  },
  {
    slug: "modern-1895-을미사변",
    era: "modern",
    year: 1895,
    title: "을미사변·을미개혁",
    kind: "event",
    period: "근대-개항기",
    category: "정치",
    importance: 2,
    body: "삼국 간섭 후 일본이 명성황후를 시해한 을미사변을 일으켰고, 단발령·태양력 시행 등 을미개혁이 추진되어 을미의병이 일어났다.",
    keywords: ["을미사변", "명성황후 시해", "삼국 간섭", "을미개혁", "단발령", "태양력", "을미의병", "아관파천"],
  },
  {
    slug: "modern-1896-독립협회",
    era: "modern",
    year: 1896,
    title: "독립협회·독립신문",
    kind: "system",
    period: "근대-개항기",
    category: "사회",
    importance: 2,
    body: "서재필 등이 독립협회를 창립하고 독립신문을 발간했으며, 독립문 건립·만민 공동회·관민 공동회(헌의 6조)를 전개하였다.",
    keywords: ["독립협회", "서재필", "독립신문", "독립문", "만민 공동회", "관민 공동회", "헌의 6조", "자주 국권", "의회 설립 운동"],
    relatedTo: ["대한제국 선포"],
  },
  {
    slug: "modern-1897-대한제국",
    era: "modern",
    year: 1897,
    title: "대한제국 선포",
    kind: "event",
    period: "근대-대한제국기",
    category: "정치",
    importance: 3,
    body: "고종이 아관파천 후 환궁하여 환구단에서 황제로 즉위, 대한제국을 선포하고 광무개혁(구본신참)을 추진하였다.",
    keywords: ["대한제국", "고종", "환구단", "황제 즉위", "광무개혁", "구본신참", "대한국 국제", "양전 사업", "지계", "원수부"],
    relatedTo: ["독립협회·독립신문", "을사늑약"],
  },
  {
    slug: "modern-1904-한일의정서",
    era: "modern",
    year: 1904,
    title: "한일의정서·1차 한일협약",
    kind: "event",
    period: "근대-국권피탈기",
    category: "대외관계",
    importance: 1,
    body: "러일전쟁 중 일본이 한일의정서로 군사 요지 사용권을 얻고, 제1차 한일협약으로 메가타·스티븐스를 고문으로 파견하였다.",
    keywords: ["한일의정서", "러일전쟁", "제1차 한일협약", "고문 정치", "메가타", "스티븐스", "화폐 정리 사업"],
  },
  {
    slug: "modern-1905-을사늑약",
    era: "modern",
    year: 1905,
    title: "을사늑약",
    kind: "event",
    period: "근대-국권피탈기",
    category: "대외관계",
    importance: 3,
    body: "외교권을 박탈당하고 통감부가 설치되었다. 을사의병이 일어나고 헤이그 특사 파견·민영환 자결 등의 저항이 있었다.",
    keywords: ["을사늑약", "제2차 한일협약", "외교권 박탈", "통감부", "이토 히로부미", "을사오적", "을사의병", "민영환 자결", "장지연 시일야방성대곡"],
    relatedTo: ["대한제국 선포", "신민회"],
  },
  {
    slug: "modern-1907-헤이그",
    era: "modern",
    year: 1907,
    title: "헤이그 특사·고종 퇴위",
    kind: "event",
    period: "근대-국권피탈기",
    category: "대외관계",
    importance: 2,
    body: "고종이 헤이그 만국 평화 회의에 특사를 파견했으나 실패하고 강제 퇴위당했으며, 한일신협약(정미7조약)으로 군대가 해산되어 정미의병이 일어났다.",
    keywords: ["헤이그 특사", "이준", "이상설", "이위종", "고종 강제 퇴위", "한일신협약", "정미7조약", "군대 해산", "정미의병", "13도 창의군", "서울 진공 작전"],
  },
  {
    slug: "modern-1907-신민회",
    era: "modern",
    year: 1907,
    title: "신민회 결성",
    kind: "system",
    period: "근대-국권피탈기",
    category: "사회",
    importance: 2,
    body: "안창호·양기탁 등이 결성한 비밀 결사로 공화정을 지향하고 대성학교·오산학교·태극서관·자기회사를 운영했으며 국외 독립운동 기지(삼원보)를 건설하였다.",
    keywords: ["신민회", "안창호", "양기탁", "이승훈", "비밀 결사", "공화정", "대성학교", "오산학교", "태극서관", "삼원보", "105인 사건"],
    relatedTo: ["을사늑약"],
  },
  {
    slug: "modern-1907-국채보상운동",
    era: "modern",
    year: 1907,
    title: "국채 보상 운동",
    kind: "event",
    period: "근대-국권피탈기",
    category: "경제",
    importance: 2,
    body: "대구에서 시작되어 대한매일신보 등의 후원으로 전국으로 확산된 일본 차관 1300만 원을 갚자는 경제적 구국 운동이다.",
    keywords: ["국채 보상 운동", "대구", "서상돈", "김광제", "대한매일신보", "차관", "금연 운동", "경제적 구국 운동"],
  },
  {
    slug: "modern-1909-안중근",
    era: "modern",
    year: 1909,
    title: "안중근 의거",
    kind: "person",
    period: "근대-국권피탈기",
    category: "대외관계",
    importance: 2,
    body: "안중근이 하얼빈에서 초대 통감 이토 히로부미를 사살하였고, 옥중에서 동양 평화론을 저술하였다.",
    keywords: ["안중근", "하얼빈", "이토 히로부미", "동양 평화론", "단지 동맹", "뤼순 감옥"],
  },

  // ==================== 일제 강점기 (japanese) ====================
  {
    slug: "japanese-1910-국권피탈",
    era: "japanese",
    year: 1910,
    title: "국권 피탈·무단 통치",
    kind: "event",
    period: "일제-무단통치기",
    category: "정치",
    importance: 3,
    body: "한일 병합으로 국권을 상실하고 조선 총독부가 설치되었으며, 헌병 경찰제·태형·토지 조사 사업 등 무단 통치가 시작되었다.",
    keywords: ["국권 피탈", "한일 병합", "조선 총독부", "무단 통치", "헌병 경찰제", "조선 태형령", "토지 조사 사업", "회사령", "1910년대"],
    relatedTo: ["3·1 운동"],
  },
  {
    slug: "japanese-1912-토지조사",
    era: "japanese",
    year: 1912,
    title: "토지 조사 사업",
    kind: "system",
    period: "일제-무단통치기",
    category: "경제",
    importance: 2,
    body: "기한부 신고제로 토지를 약탈하여 총독부 소유지를 늘리고 동양척식주식회사를 통해 일본인에게 불하, 농민의 경작권을 박탈하였다.",
    keywords: ["토지 조사 사업", "기한부 신고제", "동양척식주식회사", "토지 약탈", "회사령", "농민 몰락", "지주 강화"],
  },
  {
    slug: "japanese-1919-3·1운동",
    era: "japanese",
    year: 1919,
    title: "3·1 운동",
    kind: "event",
    period: "일제-무단통치기",
    category: "사회",
    importance: 3,
    body: "민족 대표 33인의 독립 선언과 함께 전국적 만세 시위가 일어났으며, 대한민국 임시정부 수립과 일제 통치 방식 전환(문화 통치)의 계기가 되었다.",
    keywords: ["3·1 운동", "민족 대표 33인", "독립 선언서", "기미독립선언", "만세 시위", "유관순", "제암리 학살", "탑골 공원", "민족 자결주의"],
    relatedTo: ["대한민국 임시정부", "국권 피탈·무단 통치"],
  },
  {
    slug: "japanese-1919-임시정부",
    era: "japanese",
    year: 1919,
    title: "대한민국 임시정부 수립",
    kind: "system",
    period: "일제-문화통치기",
    category: "정치",
    importance: 3,
    body: "3·1 운동 직후 상하이에서 민주 공화제 임시정부가 수립되어 연통제·교통국을 운영하고 독립 공채를 발행하였다.",
    keywords: ["대한민국 임시정부", "상하이", "민주 공화제", "연통제", "교통국", "독립 공채", "이승만", "이동휘", "국민 대표 회의", "독립신문"],
    relatedTo: ["3·1 운동", "윤봉길 의거", "한국광복군 창설"],
  },
  {
    slug: "japanese-1920-봉오동청산리",
    era: "japanese",
    year: 1920,
    title: "봉오동·청산리 전투",
    kind: "war",
    period: "일제-문화통치기",
    category: "대외관계",
    importance: 3,
    body: "홍범도의 대한독립군이 봉오동에서, 김좌진의 북로 군정서 등이 청산리에서 일본군에 큰 승리를 거두었다. 이후 간도 참변·자유시 참변이 이어졌다.",
    keywords: ["봉오동 전투", "청산리 전투", "홍범도", "대한독립군", "김좌진", "북로 군정서", "간도 참변", "자유시 참변", "독립군"],
    relatedTo: ["3·1 운동"],
  },
  {
    slug: "japanese-1920-산미증식",
    era: "japanese",
    year: 1920,
    title: "산미 증식 계획",
    kind: "system",
    period: "일제-문화통치기",
    category: "경제",
    importance: 2,
    body: "일본의 식량 부족을 해결하려 추진된 쌀 증산 정책으로, 증산량보다 많은 쌀이 일본으로 반출되어 조선 농민의 식량 사정이 악화되었다.",
    keywords: ["산미 증식 계획", "쌀 수탈", "문화 통치", "1920년대", "수리 조합", "농민 부담", "쌀 반출"],
  },
  {
    slug: "japanese-1920-물산장려",
    era: "japanese",
    year: 1920,
    title: "물산 장려 운동",
    kind: "event",
    period: "일제-문화통치기",
    category: "경제",
    importance: 2,
    body: "조만식 등이 평양에서 시작한 국산품 애용 운동으로 '내 살림 내 것으로'를 표방하며 민족 자본 육성을 꾀하였다.",
    keywords: ["물산 장려 운동", "조만식", "평양", "국산품 애용", "내 살림 내 것으로", "조선 물산 장려회", "민족 자본"],
  },
  {
    slug: "japanese-1919-의열단",
    era: "japanese",
    year: 1919,
    title: "의열단 조직",
    kind: "system",
    period: "일제-문화통치기",
    category: "대외관계",
    importance: 2,
    body: "김원봉이 만주에서 조직한 의열 투쟁 단체로 신채호의 조선혁명선언을 지침으로 삼아 식민 통치 기관 파괴와 요인 암살을 전개하였다.",
    keywords: ["의열단", "김원봉", "신채호", "조선혁명선언", "의열 투쟁", "김상옥", "나석주", "박재혁", "조선 의용대"],
  },
  {
    slug: "japanese-1926-6·10만세",
    era: "japanese",
    year: 1926,
    title: "6·10 만세 운동",
    kind: "event",
    period: "일제-문화통치기",
    category: "사회",
    importance: 2,
    body: "순종의 인산일을 계기로 학생과 사회주의·민족주의 세력이 만세 시위를 벌였고, 이는 민족 협동 전선(신간회)의 계기가 되었다.",
    keywords: ["6·10 만세 운동", "순종 인산일", "학생", "사회주의", "민족 유일당", "신간회 배경"],
  },
  {
    slug: "japanese-1927-신간회",
    era: "japanese",
    year: 1927,
    title: "신간회 창립",
    kind: "system",
    period: "일제-문화통치기",
    category: "사회",
    importance: 3,
    body: "비타협적 민족주의와 사회주의가 연합한 민족 유일당으로 일제 강점기 최대 합법 단체였으며, 광주 학생 항일 운동에 조사단을 파견하였다.",
    keywords: ["신간회", "민족 유일당", "비타협적 민족주의", "사회주의", "이상재", "정우회 선언", "근우회", "광주 학생 운동 조사단", "최대 합법 단체"],
    relatedTo: ["광주 학생 항일 운동"],
  },
  {
    slug: "japanese-1929-광주학생",
    era: "japanese",
    year: 1929,
    title: "광주 학생 항일 운동",
    kind: "event",
    period: "일제-문화통치기",
    category: "사회",
    importance: 3,
    body: "광주에서 한일 학생 충돌을 계기로 전국으로 확산된, 3·1 운동 이후 최대 규모의 학생 항일 운동이다.",
    keywords: ["광주 학생 항일 운동", "한일 학생 충돌", "나주역", "학생 운동", "신간회", "동맹 휴학", "전국 확산"],
    relatedTo: ["신간회 창립"],
  },
  {
    slug: "japanese-1931-한인애국단",
    era: "japanese",
    year: 1931,
    title: "한인 애국단 조직",
    kind: "system",
    period: "일제-민족말살기",
    category: "대외관계",
    importance: 2,
    body: "김구가 임시정부의 침체를 타개하고자 상하이에서 조직한 의열 투쟁 단체로 이봉창·윤봉길 의거를 이끌었다.",
    keywords: ["한인 애국단", "김구", "이봉창", "윤봉길", "의열 투쟁", "상하이"],
    relatedTo: ["윤봉길 의거"],
  },
  {
    slug: "japanese-1932-윤봉길",
    era: "japanese",
    year: 1932,
    title: "윤봉길 의거",
    kind: "person",
    period: "일제-민족말살기",
    category: "대외관계",
    importance: 3,
    body: "한인 애국단의 윤봉길이 상하이 훙커우 공원에서 폭탄을 던져 일본군 수뇌부를 처단, 중국 국민당의 임시정부 지원을 이끌어냈다.",
    keywords: ["윤봉길", "한인 애국단", "상하이", "훙커우 공원", "의거", "중국 국민당 지원", "이봉창"],
    relatedTo: ["대한민국 임시정부", "한국광복군 창설", "한인 애국단 조직"],
  },
  {
    slug: "japanese-1938-민족말살",
    era: "japanese",
    year: 1938,
    title: "민족 말살 통치",
    kind: "system",
    period: "일제-민족말살기",
    category: "사회",
    importance: 3,
    body: "중일전쟁 이후 일제가 황국 신민 서사 암송·신사 참배·창씨개명·국가 총동원법을 강요하며 우리말·역사 교육을 금지하였다.",
    keywords: ["민족 말살 통치", "황국 신민화", "황국 신민 서사", "신사 참배", "창씨개명", "국가 총동원법", "내선일체", "조선어 사용 금지", "중일전쟁", "징병", "징용", "일본군 위안부", "공출"],
  },
  {
    slug: "japanese-1940-광복군",
    era: "japanese",
    year: 1940,
    title: "한국광복군 창설",
    kind: "system",
    period: "일제-민족말살기",
    category: "대외관계",
    importance: 3,
    body: "대한민국 임시정부가 충칭에서 한국광복군을 창설하여 대일 선전 포고를 하고 인도·미얀마 전선 참전과 국내 진공 작전을 준비하였다.",
    keywords: ["한국광복군", "임시정부", "충칭", "지청천", "대일 선전 포고", "국내 진공 작전", "OSS", "인도 미얀마 전선", "조선 의용대 합류"],
    relatedTo: ["윤봉길 의거"],
  },
  {
    slug: "japanese-1942-조선어학회",
    era: "japanese",
    year: 1942,
    title: "조선어 학회 사건",
    kind: "event",
    period: "일제-민족말살기",
    category: "문화",
    importance: 2,
    body: "한글 연구와 우리말 큰사전 편찬을 추진하던 조선어 학회를 일제가 독립운동 단체로 몰아 탄압·해산시켰다.",
    keywords: ["조선어 학회 사건", "한글", "우리말 큰사전", "이극로", "최현배", "이윤재", "한글 맞춤법 통일안", "국어 연구"],
  },

  // ==================== 현대 (contemporary) ====================
  {
    slug: "contemporary-1945-광복",
    era: "contemporary",
    year: 1945,
    title: "8·15 광복",
    kind: "event",
    period: "현대-정부수립기",
    category: "정치",
    importance: 3,
    body: "일본의 무조건 항복으로 광복을 맞았으나, 38선을 경계로 미·소가 분할 점령하고 조선 건국 준비 위원회가 활동하였다.",
    keywords: ["8·15 광복", "일본 항복", "38선", "미군정", "소련", "조선 건국 준비 위원회", "여운형", "분단"],
    relatedTo: ["대한민국 정부 수립"],
  },
  {
    slug: "contemporary-1945-모스크바",
    era: "contemporary",
    year: 1945,
    title: "모스크바 3국 외상 회의",
    kind: "event",
    period: "현대-정부수립기",
    category: "대외관계",
    importance: 2,
    body: "한반도 임시 민주 정부 수립과 미소 공동 위원회 설치, 최대 5년 신탁 통치를 결정하여 신탁 통치를 둘러싼 좌우 대립이 격화되었다.",
    keywords: ["모스크바 3국 외상 회의", "신탁 통치", "미소 공동 위원회", "임시 민주 정부", "찬탁", "반탁", "좌우 대립"],
  },
  {
    slug: "contemporary-1948-정부수립",
    era: "contemporary",
    year: 1948,
    title: "대한민국 정부 수립",
    kind: "event",
    period: "현대-정부수립기",
    category: "정치",
    importance: 3,
    body: "5·10 총선거로 제헌 국회를 구성하고 제헌 헌법을 제정, 8월 15일 이승만을 초대 대통령으로 대한민국 정부가 수립되었다.",
    keywords: ["대한민국 정부 수립", "5·10 총선거", "제헌 국회", "제헌 헌법", "이승만", "유엔 한국 임시 위원단", "제주 4·3 사건", "단독 정부", "김구 남북 협상"],
    relatedTo: ["8·15 광복", "6·25 전쟁"],
  },
  {
    slug: "contemporary-1948-반민특위",
    era: "contemporary",
    year: 1948,
    title: "반민족 행위 처벌법·농지 개혁",
    kind: "system",
    period: "현대-정부수립기",
    category: "사회",
    importance: 2,
    body: "친일파 청산을 위한 반민특위가 구성되었으나 와해되었고, 1949년 농지 개혁법으로 유상 매수·유상 분배가 추진되었다.",
    keywords: ["반민족 행위 처벌법", "반민특위", "친일파 청산", "농지 개혁법", "유상 매수", "유상 분배", "경자유전"],
  },
  {
    slug: "contemporary-1950-6·25전쟁",
    era: "contemporary",
    year: 1950,
    title: "6·25 전쟁",
    kind: "war",
    period: "현대-정부수립기",
    category: "대외관계",
    importance: 3,
    body: "북한의 남침으로 발발, 인천 상륙 작전과 중공군 개입(1·4 후퇴)을 거쳐 1953년 정전 협정으로 휴전하였다.",
    keywords: ["6·25 전쟁", "남침", "인천 상륙 작전", "유엔군", "중공군 개입", "1·4 후퇴", "정전 협정", "휴전선", "이산가족", "반공 포로 석방"],
    relatedTo: ["대한민국 정부 수립"],
  },
  {
    slug: "contemporary-1960-4·19혁명",
    era: "contemporary",
    year: 1960,
    title: "4·19 혁명",
    kind: "event",
    period: "현대-민주화기",
    category: "정치",
    importance: 3,
    body: "3·15 부정 선거에 항거해 일어난 혁명으로 이승만 대통령이 하야하고 장면 내각의 제2공화국(내각 책임제)이 수립되었다.",
    keywords: ["4·19 혁명", "3·15 부정 선거", "이승만 하야", "김주열", "제2공화국", "장면 내각", "내각 책임제", "마산 의거"],
    relatedTo: ["6월 민주항쟁"],
  },
  {
    slug: "contemporary-1961-5·16",
    era: "contemporary",
    year: 1961,
    title: "5·16 군사 정변",
    kind: "event",
    period: "현대-산업화기",
    category: "정치",
    importance: 2,
    body: "박정희 등 군부가 정변을 일으켜 권력을 장악하고 국가 재건 최고 회의를 설치, 이후 제3공화국이 출범하였다.",
    keywords: ["5·16 군사 정변", "박정희", "군부", "국가 재건 최고 회의", "제3공화국", "경제 개발 5개년 계획"],
  },
  {
    slug: "contemporary-1965-한일협정",
    era: "contemporary",
    year: 1965,
    title: "한일 협정·베트남 파병",
    kind: "event",
    period: "현대-산업화기",
    category: "대외관계",
    importance: 2,
    body: "한일 기본 조약 체결로 국교를 정상화했으나 6·3 시위의 반발을 샀고, 베트남 파병으로 경제 개발 자금을 마련하였다.",
    keywords: ["한일 협정", "한일 기본 조약", "6·3 시위", "굴욕 외교", "베트남 파병", "브라운 각서", "경제 개발"],
  },
  {
    slug: "contemporary-1970-새마을운동",
    era: "contemporary",
    year: 1970,
    title: "새마을 운동·경부 고속도로",
    kind: "system",
    period: "현대-산업화기",
    category: "경제",
    importance: 2,
    body: "근면·자조·협동을 내건 새마을 운동이 시작되고 경부 고속도로가 개통되는 등 고도 성장과 산업화가 추진되었다.",
    keywords: ["새마을 운동", "근면 자조 협동", "경부 고속도로", "산업화", "고도 성장", "수출 주도", "경제 개발 5개년 계획", "한강의 기적"],
  },
  {
    slug: "contemporary-1972-7·4성명",
    era: "contemporary",
    year: 1972,
    title: "7·4 남북 공동 성명·유신",
    kind: "event",
    period: "현대-산업화기",
    category: "정치",
    importance: 3,
    body: "자주·평화·민족 대단결의 통일 3대 원칙에 합의한 7·4 남북 공동 성명을 발표하였으나, 같은 해 유신 헌법으로 박정희가 영구 집권 체제를 구축하였다.",
    keywords: ["7·4 남북 공동 성명", "자주", "평화", "민족 대단결", "유신 헌법", "유신 체제", "긴급 조치", "통일 주체 국민 회의", "박정희"],
    relatedTo: ["6·15 남북 공동 선언"],
  },
  {
    slug: "contemporary-1979-부마",
    era: "contemporary",
    year: 1979,
    title: "부마 민주 항쟁·10·26",
    kind: "event",
    period: "현대-민주화기",
    category: "정치",
    importance: 1,
    body: "유신 체제에 항거한 부마 민주 항쟁이 일어났고, 10·26 사태로 박정희가 피살되어 유신 체제가 막을 내렸다.",
    keywords: ["부마 민주 항쟁", "10·26 사태", "박정희 피살", "유신 체제 붕괴", "12·12 사태", "신군부"],
  },
  {
    slug: "contemporary-1980-5·18",
    era: "contemporary",
    year: 1980,
    title: "5·18 민주화 운동",
    kind: "event",
    period: "현대-민주화기",
    category: "정치",
    importance: 3,
    body: "신군부의 집권과 계엄 확대에 맞서 광주에서 일어난 민주화 운동으로, 시민군의 항쟁이 무력 진압되었다.",
    keywords: ["5·18 민주화 운동", "광주", "신군부", "전두환", "계엄 확대", "시민군", "무력 진압", "기록물 유네스코"],
    relatedTo: ["4·19 혁명", "6월 민주항쟁"],
  },
  {
    slug: "contemporary-1987-6월항쟁",
    era: "contemporary",
    year: 1987,
    title: "6월 민주 항쟁",
    kind: "event",
    period: "현대-민주화기",
    category: "정치",
    importance: 3,
    body: "박종철 고문 치사와 4·13 호헌 조치에 항거한 시위로 6·29 선언과 대통령 직선제 개헌(현행 헌법)을 이끌어냈다.",
    keywords: ["6월 민주 항쟁", "박종철", "이한열", "4·13 호헌 조치", "6·29 선언", "대통령 직선제", "5년 단임제", "호헌 철폐", "직선제 개헌"],
    relatedTo: ["5·18 민주화 운동"],
  },
  {
    slug: "contemporary-1991-남북유엔",
    era: "contemporary",
    year: 1991,
    title: "남북한 유엔 동시 가입",
    kind: "event",
    period: "현대-민주화기",
    category: "대외관계",
    importance: 1,
    body: "노태우 정부 때 남북한이 유엔에 동시 가입하고 남북 기본 합의서와 한반도 비핵화 공동 선언을 채택하였다.",
    keywords: ["남북한 유엔 동시 가입", "노태우", "남북 기본 합의서", "한반도 비핵화 공동 선언", "북방 외교"],
  },
  {
    slug: "contemporary-1997-imf",
    era: "contemporary",
    year: 1997,
    title: "IMF 외환 위기",
    kind: "event",
    period: "현대-민주화기",
    category: "경제",
    importance: 2,
    body: "외환 부족으로 IMF 구제 금융을 받게 되었고, 김대중 정부 때 금 모으기 운동과 구조 조정으로 위기를 극복하였다.",
    keywords: ["IMF 외환 위기", "구제 금융", "금 모으기 운동", "김대중 정부", "구조 조정", "기업 도산", "경제 위기"],
  },
  {
    slug: "contemporary-2000-6·15선언",
    era: "contemporary",
    year: 2000,
    title: "6·15 남북 공동 선언",
    kind: "event",
    period: "현대-민주화기",
    category: "대외관계",
    importance: 3,
    body: "김대중 대통령과 김정일 국방위원장의 분단 후 첫 남북 정상 회담 결과로 발표되어 이산가족 상봉·개성 공단·금강산 관광 등 교류로 이어졌다.",
    keywords: ["6·15 남북 공동 선언", "남북 정상 회담", "김대중", "김정일", "햇볕 정책", "이산가족 상봉", "개성 공단", "금강산 관광", "경의선 복원"],
    relatedTo: ["7·4 남북 공동 성명·유신"],
  },
  {
    slug: "contemporary-2007-남북정상",
    era: "contemporary",
    year: 2007,
    title: "제2차 남북 정상 회담",
    kind: "event",
    period: "현대-민주화기",
    category: "대외관계",
    importance: 1,
    body: "노무현 대통령과 김정일 국방위원장이 정상 회담을 갖고 10·4 남북 공동 선언(남북 관계 발전과 평화 번영 선언)을 발표하였다.",
    keywords: ["제2차 남북 정상 회담", "노무현", "김정일", "10·4 남북 공동 선언", "평화 번영"],
  },
];

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

async function backupExisting(): Promise<number> {
  const snap = await db.collection("facts").get();
  const docs = snap.docs.map((d) => ({ id: d.id, ...d.data() }));
  const outPath = join(__dirname, "facts-backup-prev.json");
  writeFileSync(outPath, JSON.stringify(docs, null, 2), "utf-8");
  console.log(`backed up ${docs.length}`);
  return docs.length;
}

async function deleteAll(): Promise<number> {
  const snap = await db.collection("facts").get();
  const refs = snap.docs.map((d) => d.ref);
  let deleted = 0;
  for (let i = 0; i < refs.length; i += 400) {
    const slice = refs.slice(i, i + 400);
    const batch = db.batch();
    for (const ref of slice) batch.delete(ref);
    await batch.commit();
    deleted += slice.length;
  }
  return deleted;
}

async function insertFacts(): Promise<number> {
  const seen = new Set<string>();
  let inserted = 0;
  for (const f of FACTS) {
    if (seen.has(f.slug)) throw new Error(`중복 slug: ${f.slug}`);
    seen.add(f.slug);
    const { slug, relatedTo, ...rest } = f;
    await db.collection("facts").doc(slug).set({
      ...rest,
      relatedTo: relatedTo ?? [],
      createdAt: Timestamp.now(),
    });
    inserted++;
  }
  return inserted;
}

async function main() {
  if (!process.env.FIRESTORE_DATABASE_ID && !process.env.FIREBASE_STORAGE_BUCKET) {
    throw new Error("환경변수 미설정(.env.local). FIRESTORE_DATABASE_ID 또는 FIREBASE_STORAGE_BUCKET 필요.");
  }
  await backupExisting();
  const deleted = await deleteAll();
  const inserted = await insertFacts();
  console.log(`deleted ${deleted}, inserted ${inserted}`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
